### ISSUE TITLE
v0.2.14 install forces python=3.6 when repro is conda-forge

### ISSUE THREAD

**Issue by dhuntley1023** [sfu-db/dataprep#462]
When creating an environment using Conda:
* This works fine: ```conda install -c conda --strict-channel-priority python=3.7 dataprep```
* This fails with a dependency error: ```conda install -c conda-forge --strict-channel-priority python=3.7 dataprep```

When using conda-forge, if you just install dataprep by itself in a new environment, the python version it selects is 3.6.  Also, note that Conda now recommends the strict channel priority option (and will soon make it default), thus the option above.

In both cases, dataprep 0.2.14 gets installed.  Are the dependency definitions identical between what was pushed to conda-forge vs. what Anaconda picked up in the conda repo?

**Comment by dhuntley1023** [comment]
I also just discovered that even with the default conda repository, dataprep will install with python=3.7, but not python=3.8 even though the dataprep readme says it should be compatible.  See below for the install error with python=3.8.  My environment is Windows 64-bit.

So to summarize:
* Conda-forge:  Max install version is python 3.6
* Conda repository: Max install version is python 3.7


**Error when attempting a dataprep + Python 3.8 install from the default conda repo:**
```
(dataprep) C:\Projects\Classes\UofM-Applied-Machine-Learning>conda create -n t1 -c conda python=3.8 dataprep
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.8
dataprep -> python
dataprep -> aiohttp[version='>=3.6.2,<4.0.0'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.5|>=3|>=3.5,<3.6.0a0|3.4.*|>=3.6|>=2.7']
Note that strict channel priority may have removed packages required for satisfiability.```

**Comment by dovahcrow** [comment]
Hi @dhuntley1023, thanks for the bug reporting! Our Conda release is less stable compared to the PyPI release due to the Conda repository is quite different from PyPI. I'm investigating the Conda package now and in the meanwhile, you can use `pip install dataprep` to install our package, even if you are using conda.

**Comment by dovahcrow** [comment]
Hi @dhuntley, since dataprep is only available in the conda-forge channel, `conda create -n t1 -c conda python=3.8 dataprep` will certainly fail. You need to add conda-forge in the channel selection: `conda create -n t1 -c conda -c conda-forge python=3.8 dataprep`.

We just released version 0.2.15 that might solve the problem since I managed to run the command `conda install -c conda-forge --strict-channel-priority python=3.7 dataprep` on docker image `continuumio/anaconda3:2019.10` (which carries python 3.7.4) without any errors.

I also managed to install dataprep with command `conda install -c conda-forge dataprep` in docker image `continuumio/anaconda3:latest` (which carries python 3.8).

Please let us know if you are still facing issues with installing the package.

**Comment by dhuntley1023** [comment]
Thanks @dovahcrow!  My condarc includes both "default" and "conda-forge" channels, with "default" as priority.

I re-executed my test cases and the 0.2.15 build seems to have fixed the problem (yea!).

Here are my Conda channel priorities as set in .condarc:
  ```
 channels:
     - defaults
     - conda-forge
   channel_priority: strict
```

**Environment creation using default as the preferred channel:  0.2.14 still fails, 0.2.15 is good**
```
  conda create -n dataprep37  python=3.8 dataprep=0.2.14  <= Failed
  conda create -n dataprep37  python=3.8 dataprep=0.2.15  <= OK
```

**Environment creation using conda-forge as the preferred channel:  0.2.14 still fails, 0.2.15 is good**
```
conda create -n dataprep37 -c conda-forge  python=3.8 dataprep=0.2.14  <= Failed
conda create -n dataprep37 -c conda-forge  python=3.8 dataprep=0.2.15 <= OK
```

**Comment by dovahcrow** [comment]
@dhuntley1023 Great! In 0.2.15 we both relaxed and removed some of the dependencies.
